config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]

  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  root :to => 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base

  # a student can have many awards
  has_many :awards, dependent: :destroy

  # a student can have many courses, a course can have many students
  has_and_belongs_to_many :courses

  validates_inclusion_of :date_of_birth, :in => Date.civil(1900, 1, 1) .. Date.today,
                         :message => "must be between January 1st, 1900 and today"

  def name
    given_name + " " + family_name
  end

  def enrolled_in?(course)
    self.courses.include?(course)
  end

  def unenrolled_courses
    Course.all - self.courses
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :courses, :course_add, :course_remove, :update, :destroy]
  before_action :check_login

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # GET /students/1/courses
  def courses
    @student = Student.find(params[:id])
    @courses = @student.courses
  end

  # POST /students/1/course_add?course_id=2
  # (note no real query string, just)
  # convenient notation for parameters
  def course_add

    #convert ids from routing to objects
    @student = Student.find(params[:id])
    @course = Course.find(params[:course])

    if not @student.enrolled_in?(@course)
      #add course to list using << @course
      @student.courses << @course
      flash[:notice] = 'Student was successfully enrolled'
    else
      flash[:error] = 'Student was already enrolled'
    end
    redirect_to :action => :courses, :id => @student
  end

  # POST /students/1/course_remove?course[]=
  def course_remove


    #get list list of courses to remove from query string
    @student = Student.find(params[:id])
    course_ids = params[:courses]

    unless course_ids.blank?
      course_ids.each do |course_id|
        course = Course.find(course_id)
        if @student.enrolled_in?(course)
          logger.info "Removing student from course #{course.id}"
          @student.courses.delete(course)
          flash[:notice] = 'Course was successfully deleted'
        end
      end
    end
    redirect_to :action => :courses, :id => @student
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:given_name, :middle_name, :family_name, :date_of_birth, :grade_point_average, :start_date)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth, :start_year => 1900, :end_year => Date.today.year %>
  </div>
  <div class="field">
    <%= f.label :grade_point_average %><br>
    <%= f.text_field :grade_point_average %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/courses.html.erb
<h1><%= @student.name %>'s courses</h1>

<% if @courses.length > 0 %>
    <%= form_tag(course_remove_student_path(@student)) do %>
        <table>
          <tr>
            <th>Course</th>
            <th>Remove?</th>
          </tr>
          <%= for course in @courses do %>
              <tr>
                <td><%= course.name %></td>
                <td><%= check_box_tag "courses[]", course.id %></td>
              </tr>
          <% end %>
        </table>
        <br />

        <%= submit_tag 'Remove checked courses' %>
    <% end %>
<% else %>
    <p>Not enrolled in any courses yet.</p>
<% end %>

<h2>Enroll in new course</h2>

<% if @student.courses.count < Course.count then %>
    <%= form_tag(course_add_student_path(@student)) do %>
        <%= select_tag(:course,
                       options_from_collection_for_select(@student.unenrolled_courses,
                                                          :id, :name)) %>
        <%= submit_tag 'Enroll' %>
    <% end %>
<% else %>
    <p><%= @student.name %> is enrolled in every course.</p>
<% end %>

<p><%= link_to 'Back', @student %></p>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
  <tr>
    <th>Given name</th>
    <th>Middle name</th>
    <th>Family name</th>
    <th>Date of birth</th>
    <th>Grade point average</th>
    <th>Start date</th>
    <th>Courses</th>
    <th>Awards</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
      <tr>
        <td class="name">
          <%= student.given_name %>
          <%= student.middle_name %>
          <%= student.family_name %>
        </td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.grade_point_average %></td>
        <td><%= student.start_date %></td>
        <td><%= student.courses.count %></td>
        <td><%= student.awards.count %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Awards', student_awards_path(student) %></td>
        <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= link_to 'Destroy', student, method: :delete, data: {confirm: 'Are you sure? This cannot be undone.'},
                            :class => 'destroy' %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>
<% if current_user.admin? %>
    <%= link_to 'New Student', new_student_path %>
<% end %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @student.given_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @student.middle_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @student.family_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @student.date_of_birth %>
</p>

<p>
  <strong>Grade point average:</strong>
  <%= @student.grade_point_average %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @student.start_date %>
</p>

<h3>Awards</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Student</th>
  </tr>

  <% @student.awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.year %></td>
        <td><%= award.student.name %></td>
      </tr>
  <% end %>
</table>

<p>
  <b>Courses:</b>
  <% if !@student.courses.empty? %>
      <%= @student.courses.collect { |c| link_to(c.name, c) }.join(", ").html_safe %>
  <% else %>
      Not enrolled in any courses yet.
  <% end %>

</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Courses', courses_student_path(@student) %> |
<%= link_to 'Awards', student_awards_path(@student) %> |
<%= link_to 'Back', students_path %>